# Generated by Django 4.1.2 on 2022-10-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtejapp', '0008_alter_order_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
