# Generated by Django 4.1.2 on 2022-11-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtejapp', '0014_alter_customer_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='nawpic.com/media/2020/messi-nawpic-10.jpg', null=True, upload_to=''),
        ),
    ]
